### ISSUE TITLE
'orange' is not a valid ctermfg

### ISSUE THREAD

**Issue by stephen-zhao** [fcpg/vim-orbital#3]
https://github.com/fcpg/vim-orbital/blob/b1f611c627a6874ad00917b74541b994f3c0acc3/colors/orbital.vim#L119

Several lines of orbital.vim's highlight commands reference the named colour 'orange', which doesn't actually exist. This causes problems with loading your colour scheme.

The error I get is:
```
Error detected while processing /home/#####/.vim/bundle/vim-orbital/colors/orbital.vim:
line  119:
E421: Color name or number not recognized: ctermfg=orange cterm=NONE
```

**Comment by fcpg** [comment]
Changed it to `darkyellow`, but couldn't really test it properly yet.
