### ISSUE TITLE
BUG: Overrides Terminal Background Color

### ISSUE THREAD

**Issue by Swivelgames** [fcpg/vim-orbital#4]
I know this probably sounds like a ridiculous bug, but I do indeed consider this a bug.

Why? Most people manage the background color through their terminal emulator. The vast majority of themes I've used out there respects this, but this one seems to override the background and make it black. The result of this is that it overrides my terminal emulator's background, which is a dark image (not solid black).

Can the background color be left to the terminal emulator please? :)

(Note: I'm not talking about bg colors for things like "`Search`" and others)

![image](https://user-images.githubusercontent.com/1456302/59219565-6ce0dd80-8b88-11e9-8e6f-93b790db0af0.png)

**Comment by fcpg** [comment]
I am a bit reluctant to change it in master since some users might rely on it, but I pushed a 'nobg' branch with all previously-black bg attributes set to "NONE".
Let me know if it works for you.

**Comment by fcpg** [comment]
No news, I'll assume it's all right.
